### ISSUE TITLE
Problem in nagiosbpi (bpi conf)

### ISSUE THREAD

**Issue by ineshmaidi** [NagiosEnterprises/nagiosbpi#10]
Problem with  nagiosbpi (bpi.conf)
When I try to add a group, it does not show up in the nagiosbpi interface. also the configuration is always incorrect (Warning: Do NOT make changes to this file unless you know what you're doing!

Error: Can't find a service with host:localhost service:Current Load, check configuration for group: 'localServices1'
Error: Can't find a service with host:localhost service:PING, check configuration for group: 'localServices1')

as soon as I delete this example the page will be all empty!!!!
ps: I use almalinux 8.9 minimum php version 8.1
also i have this error Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /var/www/html/nagiosbpi/BpGroup_class.php:805 Stack trace: #0 /var/www/html/nagiosbpi/BpGroup_class.php(596): BpGroup->determine_this_state() #1 /var/www/html/nagiosbpi/functions/bpi_functions.php(100): BpGroup->drill_down() #2 /var/www/html/nagiosbpi/index.php(69): bpi_init() #3 {main} thrown in /var/www/html/nagiosbpi/BpGroup_class.php on line 805

**Comment by derry43** [comment]
Line 805 of BpGroup_class.php is:

`if (count($this->parents > 0 ))`

Should be:

`if (count($this->parents) > 0 )`
